name: ci

on:
  push:
    paths-ignore:
    - 'doc/**'
    - 'img/**'
    - 'readme.md'
  pull_request:

jobs:
  build:
    uses: xoofx/.github/.github/workflows/dotnet.yml@main
    secrets:
      NUGET_TOKEN: ${{ secrets.NUGET_TOKEN }}

- name: Upload Test Results
  if: failure()
  uses: actions/upload-artifact@v4
  with:
    name: verify-test-results
    path: |
      **/*.received.*